spring:
  config:
    activate:
      on-profile: dev

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  web:
    resources:
      static-locations: file:./music/

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  security:
    user:
      name: none
      password: none

openai:
  api:
    key: ${OPENAI_API_KEY}
    model: ${OPENAI_API_MODEL}

suno:
  api:
    key: ${SUNO_API_KEY}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true

cloud:
  aws:
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${CLOUD_AWS_REGION_STATIC}
      auto: false
    stack:
      auto: false

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRES_MS:3600000}