spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

openai:
  api:
    key: test-key-dummy
    model: gpt-3.5-turbo

cloud:
  aws:
    credentials:
      access-key: test-access-key
      secret-key: test-secret-key
    region:
      static: ap-northeast-2
    s3:
      bucket: test-bucket

jwt:
  secret: FY+eYv3SiYg9UROpgdb3oZUbSXQEoG7C9DPkmqeL3ItNs8hD9u+MvTz1iyxXpO1YHCrqp1IkMxAsGprIN74FJA==
  expires-ms: 3600000